name: CI

on:
  pull_request:
    branches:
    - master
    
  push:
    branches:
    - master

jobs:
  build:
    runs-on: [ubuntu-latest, windows-latest, macOS-latest]
    
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        dotnet build
    - name: Test
      run: dotnet test

  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: dotnet build and test
      run: |
        dotnet build
        dotnet test
